// I'M FRIDGE — small pixel icons for the menus (12×12), drawn from text maps.
// Each letter is a colour (see PAL). "." is empty. Icons are turned into images once, at start.
// © 2026 Void Possum. All rights reserved.

var Icons = (function () {
  'use strict';

  var PAL = {
    k: '#2a1c2c', w: '#fffaf0', l: '#c3c8d4', g: '#9197a8', G: '#636a7c', s: '#14161f',
    r: '#e0483f', R: '#a8362f', y: '#ffd24a', Y: '#e0a020', b: '#4a78d0', c: '#6fe0ff',
    n: '#6cd48a', N: '#3d8043', p: '#ff6b8a', o: '#f08a2a', v: '#8a4ad0', V: '#c090f0',
    u: '#b87c4b', U: '#6c4128', e: '#f6ecd8', t: '#e8b48a'
  };

  var MAPS = {
    // ── the new park: hardware, research, side machines (0.3.1)
    rack: [
      '............',
      '..kkkkkkkk..',
      '..kGGGGGGk..',
      '..klllllnk..',
      '..kGGGGGGk..',
      '..klllllnk..',
      '..kGGGGGGk..',
      '..klllllyk..',
      '..kGGGGGGk..',
      '..klllllnk..',
      '..kkkkkkkk..',
      '..k......k..'],
    neural: [
      '............',
      '..k.k..k.k..',
      '.kkkkkkkkkk.',
      '.kppVpppVpk.',
      'kkpVppVppVkk',
      '.kppppVpppk.',
      'kkpVpppVppkk',
      '.kpppVpppVk.',
      '.kkkkkkkkkk.',
      '..k.k..k.k..',
      '............',
      '............'],
    energy: [
      '....kkkk....',
      '...kllllk...',
      '...kkkkkk...',
      '...knnnnk...',
      '...knnynk...',
      '...knyynk...',
      '...kyynnk...',
      '...knynnk...',
      '...knnnnk...',
      '...kNNNNk...',
      '...kkkkkk...',
      '............'],
    permit: [
      '............',
      '..kkkkkkkk..',
      '..keeeeeek..',
      '..kegggeek..',
      '..keeeeeek..',
      '..keggggek..',
      '..keeeeeek..',
      '..keeerrek..',
      '..keerrrek..',
      '..keeerrek..',
      '..kkkkkkkk..',
      '............'],
    vip: [
      '............',
      '............',
      '.y...yy...y.',
      '.yy..yy..yy.',
      '.yyy.yy.yyy.',
      '.yyyyyyyyyy.',
      '.yyyryyryyy.',
      '.yyyyyyyyyy.',
      '.YYYYYYYYYY.',
      '............',
      '............',
      '............'],
    sideSnack: [
      '............',
      '..kkkkkkkk..',
      '..kRrrrrRk..',
      '..kryoyork..',
      '..kroyoyrk..',
      '..krttttrk..',
      '..kryoyork..',
      '..krrrrrrk..',
      '..krkkkkrk..',
      '..kRRRRRRk..',
      '..kk....kk..',
      '............'],
    sideClaw: [
      '............',
      '..kkkkkkkk..',
      '..kRrrrrRk..',
      '..krsgssrk..',
      '..krsgssrk..',
      '..krsVpsrk..',
      '..krpVnprk..',
      '..krrrrrrk..',
      '..krkkkkrk..',
      '..kRRRRRRk..',
      '..kk....kk..',
      '............'],
    sideCoffee: [
      '............',
      '..kkkkkkkk..',
      '..kRrrrrRk..',
      '..krslslrk..',
      '..krsUUsrk..',
      '..krsUUUrk..',
      '..krsUUsrk..',
      '..krrrrrrk..',
      '..krkkkkrk..',
      '..kRRRRRRk..',
      '..kk....kk..',
      '............'],
    sideIce: [
      '............',
      '..kkkkkkkk..',
      '..kRrrrrRk..',
      '..krcwcwrk..',
      '..krwccwrk..',
      '..krcwwcrk..',
      '..krccccrk..',
      '..krrrrrrk..',
      '..krkkkkrk..',
      '..kRRRRRRk..',
      '..kk....kk..',
      '............'],
    // ── rival-only mods
    snacks: [
      '............',
      '............',
      '...kkkkkk...',
      '..keeeeeek..',
      '.kttttttttk.',
      '.knnnnnnnnk.',
      '.kpprrprrpk.',
      '.kyyyyyyyyk.',
      '.kttttttttk.',
      '..keeeeeek..',
      '...kkkkkk...',
      '............'],
    plus: [
      '............',
      '....kkkk....',
      '....kyyk....',
      '....kyyk....',
      '.kkkkyykkkk.',
      '.kyyyyyyyyk.',
      '.kyyyyyyyyk.',
      '.kkkkyykkkk.',
      '....kyyk....',
      '....kyyk....',
      '....kkkk....',
      '............'],
    // ── hardware
    script: [
      '............',
      'kkkkkkkkkkkk',
      'kgrgygnggggk',
      'kkkkkkkkkkkk',
      'kssssssssssk',
      'kscssssssssk',
      'ksscsssssssk',
      'kscsswwwsssk',
      'kssssssssssk',
      'kssssssssssk',
      'kkkkkkkkkkkk',
      '............'],
    ram: [
      '............',
      '............',
      '............',
      'kkkkkkkkkkkk',
      'knnnnnnnnnnk',
      'knkkknnkkknk',
      'knkkknnkkknk',
      'knnnnnnnnnnk',
      'kyykyykyykyk',
      'kkkkkkkkkkkk',
      '............',
      '............'],
    fan: [
      '..kkkkkkkk..',
      '.kGGGGGGGGk.',
      'kGGllGGGGGGk',
      'kGGlllGGcGGk',
      'kGGGllGccGGk',
      'kGGGGkkGGGGk',
      'kGGGGkkGGGGk',
      'kGGccGllGGGk',
      'kGGcGGlllGGk',
      'kGGGGGGllGGk',
      '.kGGGGGGGGk.',
      '..kkkkkkkk..'],
    chip: [
      '............',
      '...k.k.k.k..',
      '..kkkkkkkkk.',
      'kkkGGGGGGGkk',
      '..kGllllGGk.',
      'kkkGlccclGkk',
      '..kGlccclGk.',
      'kkkGlllllGkk',
      '..kGGGGGGGk.',
      '..kkkkkkkkk.',
      '...k.k.k.k..',
      '............'],
    chipHot: [
      '...y...y....',
      '..yry.yry...',
      '..kkkkkkkkk.',
      'kkkGGGGGGGkk',
      '..kGllllGGk.',
      'kkkGlrrrlGkk',
      '..kGlryrlGk.',
      'kkkGlllllGkk',
      '..kGGGGGGGk.',
      '..kkkkkkkkk.',
      '...k.k.k.k..',
      '............'],
    gpu: [
      '............',
      '............',
      'kkkkkkkkkkkk',
      'kGGGGGGGGGGk',
      'kGkkkGGkkkGk',
      'kkglgkkglgkk',
      'kkllckkllckk',
      'kkglgkkglgkk',
      'kGkkkGGkkkGk',
      'kkkkkkkkkkkk',
      '.yky.yky....',
      '............'],
    // ── machine upgrades
    slots: [
      '............',
      '.kkk.kkk.kkk',
      '.krk.knk.kok',
      '.kwk.kwk.kwk',
      '.krk.knk.kok',
      '.kRk.kNk.kok',
      '.kkk.kkk.kkk',
      '.kkk.kkk.kkk',
      '.krk.knk.kok',
      '.kwk.kwk.kwk',
      '.kRk.kNk.kok',
      '.kkk.kkk.kkk'],
    coin: [
      '............',
      '...kkkkkk...',
      '..kyyyyyyk..',
      '.kyywwyyyYk.',
      '.kywyyyyyYk.',
      '.kyyyYYyyYk.',
      '.kyyyYYyyYk.',
      '.kyyyyyyyYk.',
      '.kyyyyyyYYk.',
      '..kYYYYYYk..',
      '...kkkkkk...',
      '............'],
    cool: [
      '.....k......',
      '...k.c.k....',
      '....kck.....',
      '.k...c...k..',
      '..cc.c.cc...',
      'kccccwccccck',
      '..cc.c.cc...',
      '.k...c...k..',
      '....kck.....',
      '...k.c.k....',
      '.....k......',
      '............'],
    sign: [
      '............',
      'kkkkkkkkkkkk',
      'kssssssssssk',
      'ksrsrsrsrssk',
      'ksrsrsrrrssk',
      'ksrrrsrsrssk',
      'kssssssssssk',
      'kkkkkkkkkkkk',
      '...kGk.kGk..',
      '...kGk.kGk..',
      '............',
      '............'],
    drone: [
      '............',
      'lll.....lll.',
      '.k.......k..',
      '.kkkkkkkkk..',
      'kglllllllgk.',
      'kggggnggggk.',
      '.kkkkkkkkk..',
      '....krk.....',
      '....krk.....',
      '....kwk.....',
      '....kRk.....',
      '....kkk.....'],
    lemon: [
      '............',
      '....kkkk....',
      '...kllllk...',
      '...knnNnk...',
      '...knNNnk...',
      '...knwwnk...',
      '...knnnnk...',
      '...kyyyyk...',
      '...knnnnk...',
      '...knnnnk...',
      '...kllllk...',
      '....kkkk....'],
    orange: [
      '............',
      '....kkkk....',
      '...kllllk...',
      '...kooyok...',
      '...koyyok...',
      '...kowwok...',
      '...kooook...',
      '...koyyok...',
      '...kooook...',
      '...kooook...',
      '...kllllk...',
      '....kkkk....'],
    grape: [
      '............',
      '....kkkk....',
      '...kllllk...',
      '...kvvVvk...',
      '...kvVVvk...',
      '...kvwwvk...',
      '...kvvvvk...',
      '...kvVVvk...',
      '...kvvvvk...',
      '...kvvvvk...',
      '...kllllk...',
      '....kkkk....'],
    dispenser: [
      'kkkkkkkkkkkk',
      'krrrrrrrrrrk',
      'krssrrrssrrk',
      'krssrrrssrrk',
      'krrrrrrrrrrk',
      'krkkkrrkkkrk',
      'krkwkrrkwkrk',
      'krkkkrrkkkrk',
      'krrrrrrrrrrk',
      'kRRRRRRRRRRk',
      'kkkkkkkkkkkk',
      '.k........k.'],
    // ── research
    phone: [
      '...kkkkk....',
      '..kGGGGGk...',
      '..kccccck...',
      '..kcpcpck...',
      '..kcpppck...',
      '..kccpcck...',
      '..kccccck...',
      '..kccccck...',
      '..kGGGGGk...',
      '..kGGlGGk...',
      '...kkkkk....',
      '............'],
    hash: [
      '............',
      '...k...k....',
      '..kbk.kbk...',
      '.kkbkkkbkk..',
      '.kbbbbbbbk..',
      '.kkbkkkbkk..',
      '..kbk.kbk...',
      '.kkbkkkbkk..',
      '.kbbbbbbbk..',
      '.kkbkkkbkk..',
      '..kbk.kbk...',
      '...k...k....'],
    radar: [
      '..kkkkkkk...',
      '.knnNNNnnk..',
      'knNNnnnNNnk.',
      'knNnNNNnNnk.',
      'knNnNyNnNnk.',
      'knNnNNNnNnk.',
      'knNNnnnNNnk.',
      '.knnNNNnnk..',
      '..kkkkkkk...',
      '............',
      '............',
      '............'],
    pen: [
      '.........kk.',
      '........kppk',
      '.......kyykk',
      '......kyyk..',
      '.....kyyk...',
      '....kyyk....',
      '...kyyk.....',
      '..keek......',
      '..kek.......',
      '..kk........',
      '.k..........',
      '............'],
    // ── tabs
    tabHardware: null,   // uses chip
    tabMachine: [
      '..kkkkkkkk..',
      '..krrrrrrk..',
      '..krsssrrk..',
      '..krscsrrk..',
      '..krrrrrrk..',
      '..krwwwrrk..',
      '..krwwwrkk..',
      '..krwwwrrk..',
      '..krrrrrrk..',
      '..krkkkrrk..',
      '..kRRRRRRk..',
      '..kkkkkkkk..'],
    tabResearch: [
      '....kkkk....',
      '....kwwk....',
      '....kwwk....',
      '....kwwk....',
      '...kwwwwk...',
      '...kwwwwk...',
      '..kwccccwk..',
      '..kccwccck..',
      '.kccccccwck.',
      '.kcwcccccck.',
      '.kkkkkkkkkk.',
      '............'],
    tabCards: [
      '..kkkkkkkk..',
      '..kyyyyyyk..',
      '..kykkkkyk..',
      '..kyeeeeyk..',
      '..kyeppeyk..',
      '..kyeppeyk..',
      '..kyeeeeyk..',
      '..kykkkkyk..',
      '..kyeeeeyk..',
      '..kyyyyyyk..',
      '..kkkkkkkk..',
      '............'],
    tabInside: [
      '............',
      '.kkkkkkkkk..',
      '.krrrrrrrk..',
      '.kkkkkkkkk..',
      '.kgnngnngk..',
      '.kgnngnngk.k',
      '.kgggggggkkk',
      '.kgyyggyykk.',
      '.kgyyggyyk..',
      '.kgggggggk..',
      '.kkkkkkkkk..',
      '............'],
    tabBook: [
      '............',
      '.kkkkk.kkkkk',
      'kueeeekeeeek',
      'kuekkekekkek',
      'kueeeekeeeek',
      'kuekkekekkek',
      'kueeeekeeeek',
      'kuekkekekkek',
      'kueeeekeeeek',
      'kuuuuuuuuuuk',
      '.kkkkkkkkkk.',
      '............'],
    tabCustomers: [
      '....kkkk....',
      '...kUUUUk...',
      '...kUttUk...',
      '...kttttk...',
      '...kttttk...',
      '....kttk....',
      '..kkbbbbkk..',
      '.kbbbwwbbbk.',
      '.kbbbwwbbbk.',
      '.kbbbwwbbbk.',
      '.kkkkkkkkkk.',
      '............'],
    tabLog: [
      '.kkkkkkkkk..',
      'keeeeeeeeek.',
      'kekkkkkkeek.',
      'keeeeeeeeek.',
      'kekkkkkeeek.',
      'keeeeeeeeek.',
      'kekkkkkkkek.',
      'keeeeeeeeek.',
      'kekkkkeeeek.',
      'keeeeeeeeek.',
      '.kkkkkkkkk..',
      '............'],
    tabSettings: [
      '.....kk.....',
      '..kk.gg.kk..',
      '..kgggggggk.',
      '...gggkggg..',
      '.kggkk.kggk.',
      'kgggk...gggk',
      'kgggk...gggk',
      '.kggk..kggk.',
      '...gggkggg..',
      '..kgggggggk.',
      '..kk.gg.kk..',
      '.....kk.....'],
    carpet: [
      '............',
      '............',
      'w.w.w.w.w.w.',
      'kkkkkkkkkkkk',
      'krrrrrrrrrrk',
      'krRRRRRRRRrk',
      'krRyRRRRyRrk',
      'krRRRyyRRRrk',
      'krRRRRRRRRrk',
      'krrrrrrrrrrk',
      'kkkkkkkkkkkk',
      'w.w.w.w.w.w.'],
    pause: [
      '............',
      '..kkk..kkk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kwk..kwk..',
      '..kkk..kkk..',
      '............'],
    heart: [
      '............',
      '.kkk...kkk..',
      'kpppk.kpppk.',
      'kpwppkppppk.',
      'kpwpppppppk.',
      'kpppppppppk.',
      '.kpppppppk..',
      '..kpppppk...',
      '...kpppk....',
      '....kpk.....',
      '.....k......',
      '............'],
    bits: [
      '............',
      '..kk....kk..',
      '.kcck..kcck.',
      '.kcck..kcck.',
      '..kk....kk..',
      '............',
      '.....kk.....',
      '....kcck....',
      '....kcck....',
      '.....kk.....',
      '............',
      '............'],
    // ── M1.8: tubes, keyboards, fizz
    tube: [
      '..kkkk......',
      '..kllk......',
      '..klck......',
      '..kllk......',
      '..kllkkkkkk.',
      '..klllllllk.',
      '..kllllrrlk.',
      '..klllllllk.',
      '..kkkkkkkk..',
      '............',
      '............',
      '............'],
    key: [
      '............',
      '............',
      'kkkkkkkkkkkk',
      'kwlwlwlwlwlk',
      'kllllllllllk',
      'klwlwlwlwllk',
      'kllllllllllk',
      'klwwwwwwwwlk',
      'kkkkkkkkkkkk',
      '............',
      '............',
      '............'],
    fizz: [
      '............',
      '.....kkk....',
      '....kcwck...',
      '....kccck...',
      '.kkk.kkk....',
      'kcwck.......',
      'kccck..kk...',
      '.kkk..kwck..',
      '......kcck..',
      '.......kk...',
      '............',
      '............']
  };
  MAPS.tabHardware = MAPS.chip;

  var cache = {};

  function draw(name, scale) {
    var map = MAPS[name];
    if (!map) return null;
    scale = scale || 1;
    var cv = document.createElement('canvas');
    cv.width = 12 * scale; cv.height = 12 * scale;
    var g = cv.getContext('2d');
    for (var y = 0; y < map.length; y++) {
      for (var x = 0; x < 12; x++) {
        var ch = map[y][x];
        if (!ch || ch === '.') continue;
        g.fillStyle = PAL[ch] || '#ff00ff';
        g.fillRect(x * scale, y * scale, scale, scale);
      }
    }
    return cv;
  }

  // An <img> tag for an icon (as HTML text).
  function img(name, cls) {
    if (!MAPS[name]) name = 'chip';
    if (!cache[name]) cache[name] = draw(name, 1).toDataURL();
    return '<img class="ico' + (cls ? ' ' + cls : '') + '" src="' + cache[name] + '" alt="">';
  }

  return { img: img, draw: draw, has: function (n) { return !!MAPS[n]; } };
})();
