// I'M FRIDGE — writes docs/game-data.md: every upgrade, hardware item, research, Refresh star, card, rival and
// balance number, read from the real data files. Run it for every shared build:  node tools/gen-docs.js
// (The same sections are shown, and can be edited, on tools/wiki.html.)
// © 2026 Void Possum. All rights reserved.

'use strict';
var fs = require('fs');
var path = require('path');
var vm = require('vm');

var root = path.join(__dirname, '..');
var files = ['core.js', 'cards.js', 'rivals.js', 'story.js', 'machine.js', 'hardware.js', 'research.js', 'tree.js', 'news.js', 'side.js'];
var src = {};
files.forEach(function (f) {
  src[f] = fs.readFileSync(path.join(root, 'js/data', f), 'utf8');
  vm.runInThisContext(src[f], { filename: f });
});
vm.runInThisContext(fs.readFileSync(path.join(__dirname, 'describe.js'), 'utf8'), { filename: 'describe.js' });

function cell(c) {
  if (!c) return '';
  var t;
  if (c.path) t = Wiki.show(c.kind, c.v);
  else if (c.icon) t = '';
  else t = c.t == null ? '' : String(c.t);
  return t.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

var out = [];
out.push('# I\'m Fridge — game data');
out.push('');
out.push('_Generated by `node tools/gen-docs.js` from the game\'s data files (version ' + DATA.version + '). Do not edit this file by hand: ' +
         'change the data files, or use the wiki page (Konami code in the game) and send the exported change list._');
out.push('');
out.push('© 2026 Void Possum. All rights reserved.');
out.push('');
var S = Wiki.build(DATA, src);
out.push('## Contents');
S.forEach(function (s) { out.push('- [' + s.title + '](#' + s.title.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-') + ')'); });
out.push('');
S.forEach(function (s) {
  out.push('## ' + s.title);
  out.push('');
  if (s.intro) { out.push('_' + s.intro + '_'); out.push(''); }
  s.blocks.forEach(function (b) {
    if (b.type === 'text') { out.push(b.text); out.push(''); return; }
    var keep = b.cols.map(function (h, i) { return !(h === '' && b.rows.every(function (r) { return r[i] && r[i].icon; })); });
    var cols = b.cols.filter(function (h, i) { return keep[i]; });
    out.push('### ' + b.title);
    out.push('');
    out.push('| ' + cols.map(function (h) { return h || ' '; }).join(' | ') + ' |');
    out.push('|' + cols.map(function () { return ' --- '; }).join('|') + '|');
    b.rows.forEach(function (r) { out.push('| ' + r.filter(function (c, i) { return keep[i]; }).map(cell).join(' | ') + ' |'); });
    out.push('');
    if (b.note) { out.push('_' + b.note + '_'); out.push(''); }
  });
});

var dest = path.join(root, 'docs', 'game-data.md');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out.join('\n'));
console.log('Wrote ' + path.relative(root, dest) + ': ' + S.length + ' sections, ' +
  S.reduce(function (n, s) { return n + s.blocks.filter(function (b) { return b.type === 'table'; }).reduce(function (m, b) { return m + b.rows.length; }, 0); }, 0) + ' table rows.');
